# Generated by Django 5.1.4 on 2026-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('service', models.CharField(blank=True, choices=[('custom', 'Custom Website Development'), ('business', 'Business Website'), ('realestate', 'Real Estate Website'), ('ecommerce', 'E-Commerce Store'), ('landing', 'Landing Page'), ('redesign', 'Website Redesign'), ('seo', 'SEO Optimization'), ('maintenance', 'Website Maintenance'), ('ai', 'AI Chatbot Integration'), ('performance', 'Performance Optimization'), ('other', 'Άλλο')], max_length=50, verbose_name='Υπηρεσία')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('is_read', models.BooleanField(default=False, verbose_name='Διαβάστηκε')),
            ],
            options={
                'verbose_name': 'Μήνυμα Επικοινωνίας',
                'verbose_name_plural': 'Μηνύματα Επικοινωνίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('client_name', models.CharField(max_length=200, verbose_name='Όνομα Πελάτη')),
                ('industry', models.CharField(max_length=100, verbose_name='Κλάδος')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('case_study', models.TextField(blank=True, verbose_name='Case Study')),
                ('technologies', models.CharField(max_length=500, verbose_name='Τεχνολογίες (κόμμα)')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Εικόνα')),
                ('live_url', models.URLField(blank=True, verbose_name='Live URL')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Έργο',
                'verbose_name_plural': 'Έργα',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('client_role', models.CharField(max_length=200, verbose_name='Ρόλος')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Εταιρεία')),
                ('content', models.TextField(verbose_name='Κείμενο')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Βαθμολογία')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
            ],
            options={
                'verbose_name': 'Μαρτυρία',
                'verbose_name_plural': 'Μαρτυρίες',
                'ordering': ['order'],
            },
        ),
    ]
