# Generated by Django 5.1.4 on 2026-07-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('business_name', models.CharField(max_length=200, verbose_name='Επιχείρηση')),
                ('business_type', models.CharField(max_length=120, verbose_name='Τύπος επιχείρησης')),
                ('service_needed', models.CharField(max_length=120, verbose_name='Τι χρειάζεται')),
                ('current_url', models.URLField(blank=True, verbose_name='Υπάρχουσα σελίδα')),
                ('logo', models.ImageField(blank=True, upload_to='briefs/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Κινητό')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Διεύθυνση')),
                ('budget', models.CharField(blank=True, max_length=60, verbose_name='Budget')),
                ('timeline', models.CharField(blank=True, max_length=60, verbose_name='Χρονοδιάγραμμα')),
                ('vision', models.TextField(blank=True, verbose_name='Όραμα / Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('is_read', models.BooleanField(default=False, verbose_name='Διαβάστηκε')),
            ],
            options={
                'verbose_name': 'Αίτημα Project',
                'verbose_name_plural': 'Αιτήματα Project',
                'ordering': ['-created_at'],
            },
        ),
    ]
