# Generated by Django 5.1.4 on 2026-07-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectbrief'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('path', models.CharField(max_length=200, verbose_name='Σελίδα')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Επισκέψεις')),
            ],
            options={
                'verbose_name': 'Επισκεψιμότητα',
                'verbose_name_plural': 'Επισκεψιμότητα',
                'ordering': ['-date', '-count'],
                'unique_together': {('date', 'path')},
            },
        ),
    ]
