# Generated by Django 5.1.4 on 2026-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_dailyvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='status',
            field=models.CharField(choices=[('new', 'Νέο'), ('answered', 'Απάντησα'), ('won', 'Κλείστηκε ✔'), ('lost', 'Δεν προχώρησε')], default='new', max_length=12, verbose_name='Κατάσταση'),
        ),
    ]
